FacultyManagement/FacultyManagement.Web/Controllers/EducationAndAwardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FacultyManagement.Application.Common;
using FacultyManagement.Application.EducationAndAwards;
using FacultyManagement.Application.EducationAndAwards.ViewModels;
using FacultyManagement.Application.EducationAndAwards.ViewModels.Awards;
using FacultyManagement.Application.EducationAndAwards.ViewModels.Education;
using FacultyManagement.Application.EducationAndAwards.ViewModels.FacultyLanguages;
using FacultyManagement.Application.EducationAndAwards.ViewModels.Grants;
using FacultyManagement.Core.Security.Identity;
using FacultyManagement.Domain.Model;
using FacultyManagement.Domain.Model.Common;
using FacultyManagement.Domain.Model.EducationAndAwards;
using FacultyManagement.Infrastructure;
using FacultyManagement.Web.Infrastructure.Alerts;
using ControllerBase = FacultyManagement.Web.Controllers.ControllerBase;

namespace FacultyManagement.Web.Controllers
{
    public class EducationAndAwardsController : ControllerBase
    {

        public EducationAndAwardsController( IEducationAndAwardsService service ) : base( service )
        {
        }

        // GET: EducationAndAwards
        public ActionResult Index()
        {
            EducationAndAwardsVm model = null;
            try
            {
                model = Service.GetViewModel( CurrentPerson ) as EducationAndAwardsVm;
            }
            catch ( ObjectNotFoundException )
            {
                ModelState.AddModelError( "", Messages.NoDataError );
            }

            return View( model );
        }

        #region Education

        // GET: EducationAndAwards/Create
        public ActionResult CreateEducation()
        {
            var model = new EducationCreateVm( CurrentPerson.CVid );

            return PartialView( "_CreateEducation", model );
        }

        // POST: EducationAndAwards/Create
        [HttpPost]
        public ActionResult CreateEducation( EducationCreateVm model )
        {
            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            return Json( new { success } );
        }

        // GET: EducationAndAwards/Edit/5
        public ActionResult EditEducation( int id )
        {
            var model = Service.GetItem<EducationEditVm>( id, CurrentPerson );

            return PartialView( "_EditEducation", model );
        }

        // POST: EducationAndAwards/Edit/5
        [HttpPost]
        public ActionResult EditEducation( EducationEditVm model )
        {
            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            return Json( new { success } );
        }

        // GET: EducationAndAwards/Delete/5
        public ActionResult DeleteEducation( int id )
        {
            return PartialView( "_DeleteEducation", id );
        }

        // POST: EducationAndAwards/Delete/5
        [HttpPost]
        [ActionName( "DeleteEducation" )]
        public ActionResult DeleteEducationConfirmed( int id )
        {
            try
            {
                bool success = Service.Delete<Education>( id, CurrentPerson, CurrentUser );

                return Json( new { success } );
            }
            catch
            {
                return Json( new { success = false } );
            }
        }
        #endregion

        #region Awards
        public ActionResult CreateAward()
        {
            var model = new AwardCreateVm( CurrentPerson.CVid );

            return PartialView( "_CreateAward", model );
        }

        // POST: EducationAndAwards/Create
        [HttpPost]
        public ActionResult CreateAward( AwardCreateVm model )
        {
            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            return Json( new { success } );
        }

        public ActionResult EditAward( int id )
        {
            var model = Service.GetItem<AwardEditVm>( id, CurrentPerson );

            return PartialView( "_EditAward", model );
        }

        // POST: EducationAndAwards/Edit/5
        [HttpPost]
        public ActionResult EditAward( AwardEditVm model )
        {
            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            return Json( new { success } );
        }

        public ActionResult DeleteAward( int id )
        {
            return PartialView( "_DeleteAward", id );
        }

        // POST: EducationAndAwards/Delete/5
        [HttpPost]
        [ActionName( "DeleteAward" )]
        public ActionResult DeleteAwardConfirmed( int id )
        {
            try
            {
                bool success = Service.Delete<Award>( id, CurrentPerson, CurrentUser );

                return Json( new { success } );
            }
            catch
            {
                return Json( new { success = false } );
            }
        }
        #endregion

        #region Grants
        public ActionResult CreateGrant()
        {
            var model = new GrantCreateVm( CurrentPerson.CVid );

            return PartialView( "_CreateGrant", model );
        }

        // POST: EducationAndAwards/Create
        [HttpPost]
        public ActionResult CreateGrant( GrantCreateVm model )
        {
            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            return Json( new { success } );
        }

        public ActionResult EditGrant( int id )
        {
            var model = Service.GetItem<GrantEditVm>( id, CurrentPerson );

            return PartialView( "_EditGrant", model );
        }

        // POST: EducationAndAwards/Edit/5
        [HttpPost]
        public ActionResult EditGrant( GrantEditVm model )
        {
            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            return Json( new { success } );
        }

        public ActionResult DeleteGrant( int id )
        {
            return PartialView( "_DeleteGrant", id );
        }

        // POST: EducationAndAwards/Delete/5
        [HttpPost]
        [ActionName( "DeleteGrant" )]
        public ActionResult DeleteGrantConfirmed( int id )
        {
            try
            {
                bool success = Service.Delete<Grant>( id, CurrentPerson, CurrentUser );

                return Json( new { success } );
            }
            catch
            {
                return Json( new { success = false } );
            }
        }
        #endregion

        #region Languages

        public ActionResult CreateLanguage()
        {
            var model = ((IEducationAndAwardsService) Service).GetLanguageCreateViewModel( CurrentPerson.CVid );

            return PartialView( "_CreateLanguage", model as FacultyLanguageCreateVm );
        }

        // POST: EducationAndAwards/Create
        [HttpPost]
        public ActionResult CreateLanguage( FacultyLanguageCreateVm model )
        {
            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            return Json( new { success } );
        }

        public ActionResult DeleteLanguage( int id )
        {
            return PartialView( "_DeleteLanguage", id );
        }

        // POST: EducationAndAwards/Delete/5
        [HttpPost]
        [ActionName( "DeleteLanguage" )]
        public ActionResult DeleteLanguageConfirm( int id )
        {
            try
            {              
                bool success = Service.Delete<FacultyLanguage>( id, CurrentPerson, CurrentUser );

                return Json( new { success } );
            }
            catch
            {
                return Json( new { success = false } );
            }
        }
        #endregion
    }
}

FacultyManagement/FacultyManagement.Web/Controllers/PersonalInformationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FacultyManagement.Application.Common;
using FacultyManagement.Application.PersonalInformation;
using FacultyManagement.Application.PersonalInformation.ViewModels;
using FacultyManagement.Core.Security.Identity;
using FacultyManagement.Infrastructure;
using FacultyManagement.Web.Areas.Admin.Controllers;
using FacultyManagement.Web.Infrastructure.Alerts;
using ControllerBase = FacultyManagement.Web.Controllers.ControllerBase;
using System.Net;

namespace FacultyManagement.Web.Controllers
{   
    public class PersonalInformationController : ControllerBase
    {

        public PersonalInformationController( IPersonalInformationService service ) : base( service )
        {            
        }

        // GET: PersonalInformation
        /// Summary: Will Load the CurrentUser or the User that was Loaded from Admin
        /// <seealso cref="UsersController.LoadUser" />
        public ActionResult Index()
        {
            PersonalInformationVm model = null;
            try
            {
                model = Service.GetViewModel( CurrentPerson ) as PersonalInformationVm;
            }
            catch ( SqlException )
            {
                ModelState.AddModelError( "", Messages.DbConnectionError );
            }
            catch ( ObjectNotFoundException )
            {
                ModelState.AddModelError( "", Messages.NoDataError );
            }

            return View( model );
        }


        // GET: PersonalInformation/Edit/5
        //[NationalitySelectListPopulator]    
        public ActionResult Edit()
        {
            PersonalInformationEditVm model = null;
            try
            {
                model = ((IPersonalInformationService) Service).GetEditModel( CurrentPerson ) as PersonalInformationEditVm;
               
              
            }
            catch ( SqlException )
            {
                ModelState.AddModelError( "", Messages.DbConnectionError );
            }
            catch ( ObjectNotFoundException )
            {
                    ModelState.AddModelError( "", Messages.NoDataError );
            }
            ModelState.Clear();
            model.Biography = WebUtility.HtmlEncode(model.Biography);
            return View( model );
        }

        // POST: PersonalInformation/Edit/5
        [HttpPost]       
        public ActionResult Save( PersonalInformationEditVm model )
        {
            try
            {
                if ( !ModelState.IsValid ) return View( "Edit", model );
                //ModelState.Clear();
                //model.Biography = WebUtility.HtmlDecode(model.Biography);
             
                bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

                if ( success )
                {
                    return RedirectToAction( "Index" ).WithSuccess( Messages.SavingSuccess );
                }

                return RedirectToAction( "Index" ).WithError( Messages.SavingError );
            }

            catch
            {
                return View( "Edit", model ).WithError( Messages.SavingError );
            }
        }

    }
}

FacultyManagement/FacultyManagement.Web/Areas/Admin/Views/Shared/old.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Faculty Management</title>
    @Styles.Render( "~/content/font-awesome-css" )
    @Styles.Render( "~/Content/css" )
    @Scripts.Render( "~/bundles/modernizr" )
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @* @Html.ActionLink( "Faculty Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" } )*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if ( User.Identity.IsAuthenticated )
                    {
                        <li>@Html.ActionLink( "Personal Information", "Index", "PersonalInformation" )</li>
                        <li>@Html.ActionLink( "Education &  Awards / Grants", "Index", "EducationAndAwards" )</li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Academic, Professional, Personal
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink( "Academic & Professional Experience", "Index", "PersonalInformation" )</li>
                                <li>@Html.ActionLink( "Professional  & Personal Development", "Index", "PersonalInformation" )</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink( "Research Activities", "Index", "PersonalInformation" )</li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Loads
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink( "Teaching Load", "Index", "PersonalInformation" )</li>
                                <li>@Html.ActionLink( "Supervision Load", "Index", "PersonalInformation" )</li>
                                <li>@Html.ActionLink( "Management & Administration", "Index", "PersonalInformation" )</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Performance Management
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink( "Self Evaluation", "Index", "PersonalInformation" )</li>
                                <li>@Html.ActionLink( "Peer Evaluation", "Index", "PersonalInformation" )</li>
                                <li>@Html.ActionLink( "Supervisor Evaluation", "Index", "PersonalInformation" )</li>
                                <li>@Html.ActionLink( "My Commitment for the Year", "Index", "PersonalInformation" )</li>
                            </ul>
                        </li>



                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">
                   <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Admin
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink( "Load New User", "LoadUser", new { area = "Admin", controller = "Users" }, new { @class = "modal-link" } )</li>
                        </ul>
                    </li>

                    @if ( User.Identity.IsAuthenticated )
                    {
                        <li><a href="@Url.Action( "LogOut", "Account" )"><span class="fa fa-sign-out"></span> Log off, @User.Identity.Name</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action( "Login", "Account" )"><span class="fa fa-sign-in"></span> Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Partial( "_Alerts" )

        <div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                </div>
            </div>
        </div>

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Faculty Management</p>
        </footer>
    </div>

    @Scripts.Render( "~/bundles/jquery" )
    @Scripts.Render( "~/bundles/bootstrap" )
    @Scripts.Render( "~/bundles/jqueryval" )
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    @RenderSection( "scripts", required: false )


    <script src="~/Scripts/custom/alerts.js"></script>


    <script type="text/javascript">
        $(function () {
            // Initialize numeric spinner input boxes
            //$(".numeric-spinner").spinedit();
            // Initialize modal dialog
            // attach modal-container bootstrap attributes to links with .modal-link class.
            // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
            $('body').on('click', '.modal-link', function (e) {
                e.preventDefault();
                $(this).attr('data-target', '#modal-container');
                $(this).attr('data-toggle', 'modal');
            });
            // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
            $('body').on('click', '.modal-close-btn', function () {
                $('#modal-container').modal('hide');
            });
            //clear modal cache, so that new content can be loaded
            $('#modal-container').on('hidden.bs.modal', function () {
                $(this).removeData('bs.modal');
            });
            $('#CancelModal').on('click', function () {
                return false;
            });
        });
    </script>

</body>
</html>