FacultyManagement/FacultyManagement.Web/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using FacultyManagement.Application.Admin;
using FacultyManagement.Application.Admin.ViewModels;
using FacultyManagement.Core.Security.Authentication;
using FacultyManagement.Core.Security.Identity;
using FacultyManagement.Infrastructure.Utilities;
using FacultyManagement.Infrastructure.Utilities.ExtensionMethods;
using FacultyManagement.Web.ActionResults;
using FacultyManagement.Web.Infrastructure;
using ControllerBase = FacultyManagement.Web.Controllers.ControllerBase;

namespace FacultyManagement.Web.Areas.Admin.Controllers
{
    public class UsersController : Web.Controllers.ControllerBase
    {
        private readonly IAdminService _service;
        private readonly IAuthentication _authenticator;

        public UsersController( IAdminService service, IAuthentication authenticator )
        {
            _service = service;
            _authenticator = authenticator;
        }

        // GET: Admin/Users
        public ActionResult Autocomplete( string term , bool includeCurrentUser = false )
        {
            var model = _service.NameAutoComplete( term, CurrentUser, includeCurrentUser );

            return Json( model, JsonRequestBehavior.AllowGet );
        }

        #region Load User
        public ActionResult LoadUser()
        {
            return PartialView( "_LoadUsers" );
        }

        // POST: Admin/Users/LoadUser/5
        [HttpPost]
        public ActionResult LoadUser( string selectedUsernameAndCvid )
        {
            string username;
            string cVid;
            FacultyHelper.SplitUserDetails( selectedUsernameAndCvid, out cVid, out username );

            SetLoadedUser( cVid, username );

            return Json( new { success = true } );
        } 
        #endregion

        // GET: Admin/Users/ResetUser
        public ActionResult ResetUser()
        {
            Session["_LoadedUser"] = null;

            return RedirectToAction( "Index", "PersonalInformation", new { area = "" } );
        }

        // GET: Admin/Users/AddUser
        #region Add User
        public ActionResult AddUser()
        {
            var model = _service.GetAddUserViewModel( CurrentUser );

            return PartialView( "_AddUsers", model );
        }
        // POST: Admin/Users/Create
        [HttpPost]
        public ActionResult AddUser( List<string> selectedEmployeeIds )
        {
            AddUsersResult result = _service.AddUsers( selectedEmployeeIds, CurrentPerson );

            // Set the loaded user so we can redirect to their profile later
            if ( result.Success && result.FacultyUser != null )
            {
                SetLoadedUser( result.FacultyUser.CVid.ToString(), result.FacultyUser.SamAccountName );
            }

            return new JsonNetResult( new { success = result.Success } );
        } 
        #endregion

        #region Add / Remove Manager
        public ActionResult AddManager()
        {
            var model = _service.GetAddManagerViewModel( CurrentUser ) as AddRemoveManagerVm;

            return PartialView( "_AddRemoveManager", model );
        }

        [HttpPost]
        public ActionResult AddManager( AddRemoveManagerVm model )
        {
            if ( !ModelState.IsValid ) return Json( new { success = false, errorMessage = this.ErrorMessages }, JsonRequestBehavior.AllowGet );

            try
            {
                _service.AddManagers( model.SelectedSamAccountNames );
            }
            catch ( Exception )
            {
                return new JsonNetResult( new { success = false } );
            }

            return new JsonNetResult( new { success = true } );
        }

        public ActionResult RemoveManager()
        {
            var model = _service.GetRemoveManagerViewModel( CurrentUser ) as AddRemoveManagerVm;

            return PartialView( "_AddRemoveManager", model );
        }

        [HttpPost]
        public ActionResult RemoveManager( AddRemoveManagerVm model )
        {
            if ( !ModelState.IsValid ) return Json( new { success = false, errorMessage = this.ErrorMessages }, JsonRequestBehavior.AllowGet );

            try
            {
                _service.RemoveManagers( model.SelectedSamAccountNames );
            }
            catch ( Exception )
            {
                return new JsonNetResult( new { success = false } );
            }

            return new JsonNetResult( new { success = true } );
        }
        #endregion

        #region Private Methods

        /// <summary>
        /// Creates and Sets the loaded user in session.
        /// </summary>
        /// <param name="cvId">The cv identifier.</param>
        /// <param name="username">The username.</param>
        private void SetLoadedUser( string cvId, string username )
        {
            IPrincipal principal = _authenticator.CreatePrincipal( cvId, username );
            // Create loaded user and save to session
            var loadedUser = new LoadedUser( principal );
            Session.SetDataInSession<IUser<LoadedUser>>( "_LoadedUser", loadedUser );
        }

        #endregion
    }
}

FacultyManagement/FacultyManagement.Web/Controllers/SupervisorEvaluationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using FacultyManagement.Application.PerformanceManagement.SupervisorEvaluation.ViewModels;
using FacultyManagement.Application.PerformanceManagement.SupervisorEvaluation;
using FacultyManagement.Core.Security.Identity;
using FacultyManagement.Domain.Model.PerformanceManagement;
using FacultyManagement.Infrastructure.Utilities.ExtensionMethods;

namespace FacultyManagement.Web.Controllers
{
    public class SupervisorEvaluationController : ControllerBase
    {
        public SupervisorEvaluationController( ISupervisorEvaluationService service ) : base( service )
        {
        }

        public ActionResult SelectUser()
        {
            return PartialView( "_SelectUser" );
        }

        public ActionResult SelectUserPage()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult SelectUser( string selectedUsernameAndCvid )
        {
            string username;
            string cVid;
            SplitUserDetails( selectedUsernameAndCvid, out cVid, out username );

            // Create Peer Person and save to session
            var supervisorPerson = new CurrentPerson( cVid.AsInteger(), username );
            this.SetSupervisorPerson( supervisorPerson );

            return RedirectToAction( "Index" );
        }

        // GET: SupervisorEvaluation
        public ActionResult Index()
        {
            var supervisorPerson = this.GetSupervisorPerson();

            if ( supervisorPerson == null ) return RedirectToAction( "SelectUserPage" );

            var model = Service.GetViewModel( supervisorPerson, CurrentUser ) as SupervisorEvaluationVm;

            return PartialView( model );
        }

        // GET: SupervisorEvaluation/Create
        public ActionResult Create( string category )
        {
            var supervisorPerson = this.GetSupervisorPerson();

            var model = ((ISupervisorEvaluationService) Service).GetCreateVm( category, supervisorPerson, CurrentUser );

            return PartialView( "_Create", model );
        }

        // POST: SupervisorEvaluation/Create
        [HttpPost]
        public ActionResult Create( SupervisorEvaluationCreateItemVm model )
        {
            var supervisorPerson = this.GetSupervisorPerson();

            bool success = Service.SaveChanges( model, supervisorPerson, CurrentUser );

            // This will send back partial page to be re-rendered to keep user where they were
            if ( success )
            {
                return RedirectToAction( "Index" );
            }

            return new HttpStatusCodeResult( HttpStatusCode.BadRequest );  // 400
        }

        // GET: SupervisorEvaluation/Edit/5
        public ActionResult Edit( int id )
        {
            var supervisorPerson = this.GetSupervisorPerson();

            var model = Service.GetItem<SupervisorEvaluationEditItemVm>( id, supervisorPerson, CurrentUser );

            return PartialView( "_Edit", model );
        }

        // POST: SupervisorEvaluation/Edit/5
        [HttpPost]
        public ActionResult Edit( SupervisorEvaluationEditItemVm model )
        {
            var supervisorPerson = this.GetSupervisorPerson();

            bool success = Service.SaveChanges( model, supervisorPerson, CurrentUser );

            // This will send back partial page to be re-rendered to keep user where they were
            if ( success )
            {
                return RedirectToAction( "Index" );
            }

            return new HttpStatusCodeResult( HttpStatusCode.BadRequest );  // 400
        }

        #region Delete

        // GET: SupervisorEvaluation/Delete/5
        public ActionResult Delete( int id )
        {
            return PartialView( "_Delete", id );
        }

        // POST: SupervisorEvaluation/Delete/5
        [HttpPost]
        [ActionName( "Delete" )]
        public ActionResult DeleteConfirmed( int id )
        {
            var supervisorPerson = this.GetSupervisorPerson();

            bool success = Service.Delete<SupervisorEvaluation>( id, supervisorPerson, CurrentUser );

            // This will send back partial page to be re-rendered to keep user where they were
            if ( success )
            {
                return RedirectToAction( "Index" );
            }

            return new HttpStatusCodeResult( HttpStatusCode.BadRequest );  // 400
        }
        #endregion

        #region Private Methods
        private void SplitUserDetails( string selectedUsernameAndCvid, out string cVid, out string username )
        {
            var usernameAndCvid = selectedUsernameAndCvid.Split( ':' );
            username = usernameAndCvid[0];
            cVid = usernameAndCvid[1];
        }


        /// <summary>
        /// Sets the peer person in session
        /// </summary>
        /// <param name="peerPerson">The peer person.</param>
        private void SetSupervisorPerson( CurrentPerson supervisorPerson )
        {
            Session.SetDataInSession<IUser<CurrentPerson>>( "_SupervisorPerson", supervisorPerson );
        }
        /// <summary>
        /// Gets the peer person from session.
        /// </summary>
        /// <returns></returns>
        private IUser<CurrentPerson> GetSupervisorPerson()
        {
            return Session.GetDataFromSession<IUser<CurrentPerson>>( "_SupervisorPerson" );
        }

        #endregion
    }
}

FacultyManagement/FacultyManagement.Web/Views/SupervisorEvaluation/Index.cshtml
@model FacultyManagement.Application.PerformanceManagement.SupervisorEvaluation.ViewModels.SupervisorEvaluationVm

@{
    ViewBag.Title = "Supervisor Evaluation";
}

<h3>Supervisor x Evaluation for <strong class="text-primary">@Model.FullName</strong></h3>
<div>
    <div class="panel-group" id="accordion">
        
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><li class="fa fa-caret-down"></li> Integrity</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                    @Html.Partial( "_Evaluations", Model.Integrity )
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><li class="fa fa-caret-down"></li> Inclusivity</a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
                    @Html.Partial( "_Evaluations", Model.Inclusivity )
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><li class="fa fa-caret-down"></li> Innovation</a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
                <div class="panel-body">
                    @Html.Partial( "_Evaluations", Model.Innovation )
                </div>
            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><li class="fa fa-caret-down"></li> Engagement</a>
                </h4>
            </div>
            <div id="collapseFour" class="panel-collapse collapse">
                <div class="panel-body">
                    @Html.Partial( "_Evaluations", Model.Engagement )
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix"><li class="fa fa-caret-down"></li> Excellence</a>
                </h4>
            </div>
            <div id="collapseSix" class="panel-collapse collapse">
                <div class="panel-body">
                    @Html.Partial( "_Evaluations", Model.Excellence )
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive"><li class="fa fa-caret-down"></li> Sustainability</a>
                </h4>
            </div>
            <div id="collapseFive" class="panel-collapse collapse">
                <div class="panel-body">
                    @Html.Partial( "_Evaluations", Model.Sustainability )
                </div>
            </div>
        </div>

    </div>
</div>



 
<script src="~/Scripts/js-cookie/js.cookie-2.1.3.min.js"></script>
<script src="~/Scripts/custom/accordianCookieTracker.js"></script>

FacultyManagement/FacultyManagement.Web/Views/SupervisorEvaluation/SelectUserPage.cshtml
<div id="index">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Please Select User to Evaluate</h4>
    </div>

    <div class="modal-body">
        <div>
            @using ( Ajax.BeginForm( "SelectUser", "SupervisorEvaluation", new { area = "" },
            new AjaxOptions
            {
                LoadingElementId = "div_loading",
                UpdateTargetId = "index",
                InsertionMode = InsertionMode.Replace,
            }, null ) )
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary( true )

                <div class="form-horizontal">
                    <div class="form-group">
                        <!--Hidden value sent back to controller-->
                        <input type="hidden" name="selectedUsernameAndCvid" id="selected_user" />

                        @Html.BootstrapLabel( "User", columns: 2, required: true )
                        <div class="col-md-6">
                            <input type="search" id="faculty-user-search" name="user-search" class="ui-autocomplete form-control" data-url="@Url.Action( "Autocomplete", "Users", new {area = "Admin"} )" placeholder="Name or Surname" />
                            <div id="searchresults"></div>
                        </div>
                    </div>

                    <br />

                    <button type="submit" class="btn btn-primary">Load</button>
                </div>
            }
        </div>
    </div>

</div>



<script type="text/javascript">
    // The autocomplete element
    $("#faculty-user-search").autocomplete({
        minLength: 3,
        source: function (request, response) {
            var url = $(this.element).data("url");
            $.getJSON(url, { term: request.term }, function (data) {
                response(data);
            });
        },
        // The the element we want to update
        appendTo: $("#searchresults"),
        // This will override the label
        // and set custom input to be sent to controller with another id
        select: function (e, ui) {
            e.preventDefault() // <--- Prevent the value from being inserted.
            $("#selected_user").val(ui.item.value); // <--- custom input - we set another value

            $(this).val(ui.item.label); // <---  the search input box display text
        }
    });

</script>

FacultyManagement/FacultyManagement.Web/Views/SupervisorEvaluation/_Create.cshtml
@model FacultyManagement.Application.PerformanceManagement.SupervisorEvaluation.ViewModels.SupervisorEvaluationCreateItemVm

<div data-role="page">
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</div>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">New Evaluation</h4>
</div>

<div class="modal-body">

    <p id="MessageToClient" class="text-danger"></p>

    @using ( Ajax.BeginForm( "Create", "SupervisorEvaluation",
        new AjaxOptions
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "user-evaluations",
            OnSuccess = "closeModal",
            OnFailure = "showMessage"
        } ) )
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary( false, "", new { @class = "text-danger" } )

        @Html.HiddenFor( model => model.CVid )
        @Html.HiddenFor( model => model.Category )
        @Html.HiddenFor( model => model.SupervisorCVid )

        <div class="form-horizontal">
            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.Year, columns: 2, required: true )
                <div class="col-md-3">
                    @Html.EditorFor( model => model.SelectedYears )
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabel( "Evaluation", columns: 2, required: true )
                <div class="col-md-6">
                    @Html.EditorFor( model => model.ValueCommitment )
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.Description, columns: 2, required: true )
                <div class="col-md-10">
                    @Html.EditorFor( model => model.Description )
                </div>
           </div>

        </div>

        <br />
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    }
</div>


<script>
    function closeModal() {
        $("#modal-container").modal("hide");
    }

    function showMessage() {
        $("#MessageToClient").html("<div class='alert alert-danger'> <i class='fa fa-exclamation-triangle fa-2x'> </i> " +
            " An error has occurred while processing your request. <p> Your organization's administrators have been notified of this problem.</p></div>");
    }
</script>

FacultyManagement/FacultyManagement.Web/Views/SupervisorEvaluation/_Delete.cshtml
@model int?

<div class="modal-body">
    <div class="error-wrap">
        <h1>Confirm Delete</h1>
        <h3>Are you sure you want to delete this?</h3>

        <p class="error-icon danger">
            <i class="fa fa-times-circle"></i>
        </p>
    </div>

    <div>

        @using (Ajax.BeginForm(
            new AjaxOptions
            {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "user-evaluations",
                OnSuccess = "closeModal",
                OnFailure = "showMessage"
            } ))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden( "id", Model )
            ;

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        }
    </div>
</div>


<script>

    function closeModal() {
        $("#modal-container").modal("hide");
    }

    function showMessage() {
        $("#MessageToClient").html("<div class='alert alert-danger'> <i class='fa fa-exclamation-triangle fa-2x'> </i> " +
            " An error has occurred while processing your request. <p> Your organization's administrators have been notified of this problem.</p></div>");
    }

</script>

FacultyManagement/FacultyManagement.Web/Views/SupervisorEvaluation/_Edit.cshtml
@model FacultyManagement.Application.PerformanceManagement.SupervisorEvaluation.ViewModels.SupervisorEvaluationEditItemVm

<div data-role="page">
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</div>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Edit Evaluation</h4>
</div>

<div class="modal-body">

    <p id="MessageToClient" class="text-danger"></p>

    @using (Ajax.BeginForm( "Edit", "SupervisorEvaluation",
        new AjaxOptions
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "user-evaluations",
            OnSuccess = "closeModal",
            OnFailure = "showMessage"
        } ))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary( false, "", new { @class = "text-danger" } )

        @Html.HiddenFor( model => model.CVid )
        @Html.HiddenFor( model => model.Category )
        @Html.HiddenFor( model => model.SupervisorCVid )

        <div class="form-horizontal">
            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.Year, columns: 2, required: true )
                <div class="col-md-3">
                   @Html.EditorFor( model => model.Year )
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabel( "Evaluation", columns: 2, required: true )
                <div class="col-md-6">
                    @Html.EditorFor( model => model.ValueCommitment )
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.Description, columns: 2, required: true )
                <div class="col-md-10">
                    @Html.EditorFor( model => model.Description )
                </div>
           </div>

        </div>

        <br />
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    }
</div>


<script>
    function closeModal() {
        $("#modal-container").modal("hide");
    }

    function showMessage() {
        $("#MessageToClient").html("<div class='alert alert-danger'> <i class='fa fa-exclamation-triangle fa-2x'> </i> " +
            " An error has occurred while processing your request. <p> Your organization's administrators have been notified of this problem.</p></div>");
    }
</script>

FacultyManagement/FacultyManagement.Web/Views/SupervisorEvaluation/_Evaluations.cshtml
@model FacultyManagement.Application.PerformanceManagement.Common.EvaluationGroupVm

<div class="panel-body">
    @if ( Model.Evaluations.Any() )
            {
        <table id="client-table" class="table table-responsive table-condensed">
            <thead>
                <tr>
                    <th>
                      Year
                    </th>
                    <th>
                        Evaluation Area
                    </th>
                    <th>
                        Notes
                    </th>                  
                    <th></th>
                </tr>
            </thead>

            @foreach ( var item in Model.Evaluations )
                {
                <tr>
                    <td>
                        @Html.DisplayFor( modelItem => item.Year )
                    </td>
                    <td>
                        @Html.DisplayFor( modelItem => item.ValueCommitment )
                    </td>
                    <td>
                        @Html.DisplayFor( modelItem => item.Description )
                    </td>

                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                Actions <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink( "Edit", "Edit", new { id = item.Id }, new { @class = "modal-link" } )</li>
                                <li>@Html.ActionLink( "Delete", "Delete", new { id = item.Id }, new { @class = "modal-link" } )</li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }

        </table>
    }
    else
    {
        <p>No Records found</p>
    }
</div>
<div class="panel-footer">
    <div class="row">
        <div class="col-xs-4">
            <a href=@Url.Action( "Create", "SupervisorEvaluation", new { Model.Category } ) class="btn btn-xs btn-primary modal-link">
                <i class="fa fa-plus"></i> Add New
            </a>
        </div>
        <div class="col-xs-8">

        </div>
    </div>
</div>

FacultyManagement/FacultyManagement.Web/Views/SupervisorEvaluation/_SelectUser.cshtml
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Please Select User to Evaluate</h4>
</div>

<div class="modal-body">
    <div>
        @using ( Html.BeginForm() )
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary( true )

            <div class="form-horizontal">
                <div class="form-group">
                    <!--Hidden value sent back to controller-->
                    <input type="hidden" name="selectedUsernameAndCvid" id="selected_user" />

                    @Html.BootstrapLabel( "User", columns: 2, required: true )
                    <div class="col-md-6">
                        <input type="search" id="faculty-user-search" name="user-search" class="ui-autocomplete form-control" data-url="@Url.Action( "Autocomplete", "Users", new {area = "Admin"} )" placeholder="Name or Surname" />
                        <div id="searchresults"></div>
                    </div>
                </div>
            </div>

            <br />
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Load</button>
            </div>
        }
    </div>
</div>


<script type="text/javascript">
    // The autocomplete element
    $("#faculty-user-search").autocomplete({
        minLength: 3,
        source: function (request, response) {
            var url = $(this.element).data("url");
            $.getJSON(url, { term: request.term }, function (data) {
                response(data);
            });
        },
        // The the element we want to update
        appendTo: $("#searchresults"),
        // This will override the label
        // and set custom input to be sent to controller with another id
        select: function (e, ui) {
            e.preventDefault() // <--- Prevent the value from being inserted.
            $("#selected_user").val(ui.item.value); // <--- custom input - we set another value

            $(this).val(ui.item.label); // <---  the search input box display text
        }
    });

</script>