FacultyManagement/FacultyManagement.Web/Areas/Admin/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using FacultyManagement.Application.Admin;
using FacultyManagement.Application.Admin.ViewModels;
using FacultyManagement.Application.Admin.ViewModels.Common;
using FacultyManagement.Core.Security.Identity;
using FacultyManagement.Domain.ExtensionMethods;
using FacultyManagement.Infrastructure.Utilities;
using FacultyManagement.Infrastructure.Utilities.ExtensionMethods;
using FacultyManagement.Web.Infrastructure;
using ControllerBase = FacultyManagement.Web.Controllers.ControllerBase;

namespace FacultyManagement.Web.Areas.Admin.Controllers
{
    public class ManagementController : ControllerBase
    {

        public ManagementController(IAdminService service) : base(service)
        {
        }


        #region Departments

        // GET: Admin/Departments
        public ActionResult AddOrganisation()
        {
            var model = ((IAdminService)Service).GetSelectUserViewModel() as UserSelectBaseVm;

            return View(model);
        }

        [HttpPost]
        public ActionResult LoadUserOrganisations(string selectedUsernameAndCvid)
        {
            string username;
            string cVid;
            FacultyHelper.SplitUserDetails(selectedUsernameAndCvid, out cVid, out username);

            //Stop partial view page repeating
            if (Request.IsAjaxRequest())
            {
                var model = ((IAdminService)Service).GetOrganisations(cVid.AsInteger());

                return PartialView("_Organisations", model);
            }


            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult CreateUserOrganisations(OrganisationAndRolesVm model)
        {
            if (!ModelState.IsValid) return PartialView("_Organisations", model);

            bool success = Service.SaveChanges(model,
                                                                    new CurrentPerson(model.CVid.Value, model.Username),
                                                                    CurrentUser);

            return Json(new { success });
        }
        #endregion

        #region Classification & Sufficiency

        // GET: Admin/AddClassification
        public ActionResult AddClassification()
        {
            var model = ((IAdminService)Service).GetSelectUserViewModel() as UserSelectBaseVm;

            return View(model);
        }


        [HttpPost]
        public ActionResult LoadUserClassifications(string selectedUsernameAndCvid)
        {
            string username;
            string cVid;
            FacultyHelper.SplitUserDetails(selectedUsernameAndCvid, out cVid, out username);

            //Stop partial view page repeating
            if (Request.IsAjaxRequest())
            {
                var model = ((IAdminService)Service).GetClassificationsAndSufficiencies(cVid.AsInteger());

                return PartialView("_Classifications", model);
            }


            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult CreateUserClassifications(ClassificationsAndSufficienciesVm model)
        {
            if (!ModelState.IsValid) return PartialView("_Classifications", model);

            bool success = Service.SaveChanges(model,
                                                                    new CurrentPerson(model.CVid.Value, model.Username),
                                                                    CurrentUser);

            return Json(new { success });
        }

        #endregion

        #region Executive profile 

        public ActionResult EditExecutiveProfile()
        {
            var model = ((IAdminService)Service).GetExecutiveProfile(CurrentPerson);

            return PartialView("_EditExecutiveProfile", model);
        }

        [HttpPost]
        public ActionResult EditExecutiveProfile(ExecutiveProfileVm model)
        {
            bool success = Service.SaveChanges(model, CurrentPerson, CurrentUser);

            return Json(new { success });
        }

        public ActionResult LogOut()
        {
            Logger.Info($"Username:{this.CurrentUser.Username}");

            Request.GetOwinContext().Authentication.SignOut();
            return Redirect("/FacultyManagement");
        }


        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return Redirect("/");
        }
        #endregion
    }
}

FacultyManagement/FacultyManagement.Web/Controllers/PersonalInformationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FacultyManagement.Application.Common;
using FacultyManagement.Application.PersonalInformation;
using FacultyManagement.Application.PersonalInformation.ViewModels;
using FacultyManagement.Core.Security.Identity;
using FacultyManagement.Infrastructure;
using FacultyManagement.Web.Areas.Admin.Controllers;
using FacultyManagement.Web.Infrastructure.Alerts;
using ControllerBase = FacultyManagement.Web.Controllers.ControllerBase;
using System.Net;

namespace FacultyManagement.Web.Controllers
{   
    public class PersonalInformationController : ControllerBase
    {

        public PersonalInformationController( IPersonalInformationService service ) : base( service )
        {            
        }

        // GET: PersonalInformation
        /// Summary: Will Load the CurrentUser or the User that was Loaded from Admin
        /// <seealso cref="UsersController.LoadUser" />
        public ActionResult Index()
        {
            PersonalInformationVm model = null;
            try
            {
                model = Service.GetViewModel( CurrentPerson ) as PersonalInformationVm;
            }
            catch ( SqlException )
            {
                ModelState.AddModelError( "", Messages.DbConnectionError );
            }
            catch ( ObjectNotFoundException )
            {
                ModelState.AddModelError( "", Messages.NoDataError );
            }

            return View( model );
        }


        // GET: PersonalInformation/Edit/5
        //[NationalitySelectListPopulator]    
        public ActionResult Edit()
        {
            PersonalInformationEditVm model = null;
            try
            {
                model = ((IPersonalInformationService) Service).GetEditModel( CurrentPerson ) as PersonalInformationEditVm;
               
              
            }
            catch ( SqlException )
            {
                ModelState.AddModelError( "", Messages.DbConnectionError );
            }
            catch ( ObjectNotFoundException )
            {
                    ModelState.AddModelError( "", Messages.NoDataError );
            }
            ModelState.Clear();
            model.Biography = WebUtility.HtmlEncode(model.Biography);
            return View( model );
        }

        // POST: PersonalInformation/Edit/5
        [HttpPost]       
        public ActionResult Save( PersonalInformationEditVm model )
        {
            try
            {
                if ( !ModelState.IsValid ) return View( "Edit", model );
                //ModelState.Clear();
                //model.Biography = WebUtility.HtmlDecode(model.Biography);
             
                bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

                if ( success )
                {
                    return RedirectToAction( "Index" ).WithSuccess( Messages.SavingSuccess );
                }

                return RedirectToAction( "Index" ).WithError( Messages.SavingError );
            }

            catch
            {
                return View( "Edit", model ).WithError( Messages.SavingError );
            }
        }

    }
}

FacultyManagement/FacultyManagement.Web/Areas/Admin/Views/ExecutiveProfile/EditExecutiveProfile.cshtml
@model FacultyManagement.Application.Admin.ViewModels.ExecutiveProfileVm


<p id="MessageToClient"></p>

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel">Edit Executive Profile for <strong class="text-primary">@Model.FullName</strong></h4>
</div>

<div id="update-view">
    <div class="modal-body">
        <div>
            <div id="div_loading" style="display: none"><img src="~/Images/loader.gif" /></div>



            @using ( Ajax.BeginForm( "EditExecutiveProfile", "EditExecutiveProfile", new { area = "" },
                    new AjaxOptions
                    {
                        LoadingElementId = "div_loading",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "update-view",
                        OnSuccess = "showSuccessMessage",
                        OnFailure = "showFailureMessage"
                    } ) )
            {
                @Html.HiddenFor( model => model.CVid )


                <fieldset>
                    <div class="row">
                        <div class="col-md-12">
                            @Html.TextAreaFor( model => model.Biography )
                        </div>
                    </div>
                </fieldset>

                <br />
                <div class="modal-footer">
                    <a href="@Url.Action("Index", "PersonalInformation", new  {area=""})" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            }

        </div>
    </div>
</div>

@section Scripts {

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        function showSuccessMessage() {
            $("#MessageToClient")
                .html("<div class='alert alert-success'> <i class='fa fa-check-circle-o fa-2x'> </i> Successfully Updated.</div>");

            setTimeout(function() {                
                location.reload();
            }, 1000);
        }

        function showFailureMessage() {
            $("#MessageToClient").html("<div class='alert alert-danger'> <i class='fa fa-exclamation-triangle fa-2x'> </i> " +
                " An error has occurred while processing your request. <p> Your organization's administrators have been notified of this problem.</p></div>");
        }
    </script>
}

FacultyManagement/FacultyManagement.Web/Areas/Admin/Views/ExecutiveProfile/_EditExecutiveProfile.cshtml
@model FacultyManagement.Application.Admin.ViewModels.ExecutiveProfileVm

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Edit Executive Profile for <strong class="text-primary">@Model.FullName</strong></h4>
</div>

<div class="modal-body">
    <div>
        <div id="div_loading" style="display: none"><img src="~/Images/loader.gif" /></div>
        <p id="MessageToClient" class="text-danger"></p>

        @using ( Html.BeginForm( "EditExecutiveProfile", "Management", new {area="Admin"}, FormMethod.Post) )
        {
            @Html.HiddenFor( model => model.CVid )

            <fieldset>
                <div class="row">
                    <div class="col-md-12">
                        @Html.EditorFor( model => model.Biography )
                    </div>
                </div>
            </fieldset>

            <br />
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        }

    </div>
</div>


<script src="~/Scripts/custom/formActions.js"></script>