PerformanceManagement/PerformanceManagement/Controllers/MyCommitmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PerformanceManagement.Application.PerformanceManagement.MyCommitment;
using PerformanceManagement.Application.PerformanceManagement.MyCommitment.ViewModels;
using PerformanceManagement.Domain.Model.PerformanceManagement;
using PerformanceManagement.Web.ActionResults;

namespace PerformanceManagement.Web.Controllers
{
    public class MyCommitmentController : ControllerBase
    {
        public MyCommitmentController( IMyCommitmentService service ) : base( service )
        {
        }

        // GET: MyCommitment
        public ActionResult Index()
        {
            var model = Service.GetViewModel( CurrentPerson ) as MyCommitmentVm;

            return View( model );
        }

        // GET: MyCommitment/Create
        public ActionResult Create()
        {
            var model = new MyCommitmentCreateItemVm( this.CVid );

            return PartialView( "_Create", model );
        }

        // POST: MyCommitment/Create
        [HttpPost]
        public ActionResult Create( MyCommitmentCreateItemVm model )
        {
            if ( !ModelState.IsValid ) return Json( new { success = false, errorMessage = this.ErrorMessages }, JsonRequestBehavior.AllowGet );

            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            // This will send back partial page to be re-rendered to keep user where they were
            if ( success )
            {
                return RedirectToAction( "Index" );
            }

            return new HttpStatusCodeResult( HttpStatusCode.BadRequest );  // 400
        }

        // GET: MyCommitment/Edit/5
        public ActionResult Edit( int id )
        {
            var model = Service.GetItem<MyCommitmenteEditItemVm>( id, CurrentPerson );

            return PartialView( "_Edit", model );
        }

        // POST: MyCommitment/Edit/5
        [HttpPost]
        public ActionResult Edit( MyCommitmenteEditItemVm model )
        {
            if ( !ModelState.IsValid ) return Json( new { success = false, errorMessage = this.ErrorMessages }, JsonRequestBehavior.AllowGet );

            bool success = Service.SaveChanges( model, CurrentPerson, CurrentUser );

            // This will send back partial page to be re-rendered to keep user where they were
            if ( success )
            {
                return RedirectToAction( "Index" );
            }

            return new HttpStatusCodeResult( HttpStatusCode.BadRequest );  // 400
        }

        #region Delete

        // GET: SupervisorEvaluation/Delete/5
        public ActionResult Delete( int id )
        {
            return PartialView( "_Delete", id );
        }

        // POST: SupervisorEvaluation/Delete/5
        [HttpPost]
        [ActionName( "Delete" )]
        public ActionResult DeleteConfirmed( int id )
        {
            bool success = Service.Delete<Commitment>( id, CurrentPerson, CurrentUser );

            // This will send back partial page to be re-rendered to keep user where they were
            if ( success )
            {
                return RedirectToAction( "Index" );
            }

            return new HttpStatusCodeResult( HttpStatusCode.BadRequest );  // 400
        }
        #endregion




        // Json : Get performance categories
        public ActionResult GetPerformanceCategories()
        {
            var model = ( (IMyCommitmentService) Service ).GetPerformanceCategories();

            return new JsonNetResult( model );
        }
    }
}

PerformanceManagement/PerformanceManagement/Views/MyCommitment/Index.cshtml
@model PerformanceManagement.Application.PerformanceManagement.MyCommitment.ViewModels.MyCommitmentVm

@{
    ViewBag.Title = "My Commitments for the Year";
}

<h3>My Commitments for the Year</h3>
<div>
    <div class="panel-group" id="accordion">
        
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><li class="fa fa-caret-down"></li> Commitments</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
                <div class="panel-body">
                    @Html.Partial( "_Commitments", Model.Commitments )
                </div>
            </div>
        </div>

    </div>
</div>



@section Styles{
}

@section Scripts
{

}

PerformanceManagement/PerformanceManagement/Views/MyCommitment/_Commitments.cshtml
@model IEnumerable<PerformanceManagement.Application.PerformanceManagement.MyCommitment.ViewModels.CommitmentVm>


<div class="panel-body">
    @if ( Model.Any() )
            {
        <table id="client-table" class="table table-responsive table-condensed">
            <thead>
                <tr>
                    <th>
                       Year
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                         Category
                    </th>
                    <th>
                        Commitment
                    </th>
                    <th>
                        BaseLine
                    </th>
                    <th></th>
                </tr>
            </thead>

            @foreach ( var item in Model )
                {
                <tr>
                    <td>
                        @Html.DisplayFor( modelItem => item.Year )
                    </td>
                    <td>
                        @Html.DisplayFor( modelItem => item.Description )
                    </td>
                    <td>
                        @Html.DisplayFor( modelItem => item.PerformanceCategory )
                    </td>
                    <td>
                        @Html.DisplayFor( modelItem => item.CommitmentValue )
                    </td>
                    <td>
                        @Html.DisplayFor( modelItem => item.BaseLine )
                    </td>
                    
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                Actions <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink( "Edit", "Edit", new { id = item.Id }, new { @class = "modal-link" } )</li>
                                <li>@Html.ActionLink( "Delete", "Delete", new { id = item.Id }, new { @class = "modal-link" } )</li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }

        </table>
    }
    else
    {
        <p>No Records found</p>
    }
</div>
<div class="panel-footer">
    <div class="row">
        <div class="col-xs-4">
            <a href=@Url.Action( "Create", "MyCommitment", new {} ) class="btn btn-xs btn-primary modal-link">
                <i class="fa fa-plus"></i> Add New
            </a>
        </div>
        <div class="col-xs-8">

        </div>
    </div>
</div>

PerformanceManagement/PerformanceManagement/Views/MyCommitment/_Create.cshtml
@model PerformanceManagement.Application.PerformanceManagement.MyCommitment.ViewModels.MyCommitmentCreateItemVm

<div data-role="page">
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</div>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">New Commitment</h4>
</div>

<div class="modal-body">

    <p id="MessageToClient" class="text-danger"></p>

    @using ( Ajax.BeginForm( "Create", "MyCommitment",
                        new AjaxOptions
                        {
                            HttpMethod = "POST",
                            InsertionMode = InsertionMode.Replace,
                            UpdateTargetId = "user-evaluations",
                            OnSuccess = "closeModal",
                            OnFailure = "showMessage"
                        } ) )
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary( false, "", new { @class = "text-danger" } )

        @Html.HiddenFor( model => model.CVid )

        <div class="form-horizontal">
            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.Year, columns: 2, required: true )
                <div class="col-md-3">
                    @Html.EditorFor( model => model.Year )
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabel( "Category", columns: 2, required: true )
                <div class="col-md-6">
                    @Html.DropDownListFor( m => m.PerformanceCategoryId, Model.PerformanceCategories, new { @class = "form-control" } )
                    <input type="text" id="baseline" class="form-control" readonly="readonly">
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.CommitmentValue, columns: 2, required: true )
                <div class="col-md-10">
                    @Html.EditorFor( model => model.CommitmentValue )
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.Description, columns: 2, required: false )
                <div class="col-md-10">
                    @Html.EditorFor( model => model.Description )
                </div>
            </div>

        </div>

        <br />
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>

    }
</div>


<script>
        $(document).ready(function() {
            var dict = []; // create an empty array

            // Populate Dropdownlist
            $.ajax({
                type: 'POST',
                url: '@Url.Action( "GetPerformanceCategories" )',
                dataType: 'json',
                success: function (results) {
                    $("#PerformanceCategoryId")
                        .html("'<option selected disabled='disabled'>--Select Category--</option>'");
                    /*----------------------------------------------------------------*/
                    // results contains the JSON formatted list
                    // of states passed from the controller
                    $.each(results,
                        function(i, result) {
                            // result is the json object returned : properties are in camel case because we using Json.NET serializer
                            // result.description instead of result.escription
                            $("#PerformanceCategoryId")
                                .append('<option value="' + result.id + '">' + result.description + '</option>');

                            // create dictionary items
                            dict[result.id] = result.baseLine;
                        });
                },
                error: function(ex) {
                    alert('Failed to retrieve items.' + ex);
                }
            });

            //Dropdownlist Selectedchange event
            $('#PerformanceCategoryId').on('change', function () {
                // Get the drop down value
                var key = this.value;
                // Pull value out of dictionary using key obtained
                var value = dict[key];
                // Set the text box to the dictionary value
                $("#baseline").val(value);
            });

            return false;
    });


    function closeModal() {
        $("#modal-container").modal("hide");
    }

    function showMessage() {
        $("#MessageToClient").html("<div class='alert alert-danger'> <i class='fa fa-exclamation-triangle fa-2x'> </i> " +
            " An error has occurred while processing your request. <p> Your organization's administrators have been notified of this problem.</p></div>");
    }

</script>

PerformanceManagement/PerformanceManagement/Views/MyCommitment/_Delete.cshtml
@model int?

<div class="modal-body">
    <div class="error-wrap">
        <h1>Confirm Delete</h1>
        <h3>Are you sure you want to delete this?</h3>

        <p class="error-icon danger">
            <i class="fa fa-times-circle"></i>
        </p>
    </div>

    <div>

        @using (Ajax.BeginForm(
            new AjaxOptions
            {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "user-evaluations",
                OnSuccess = "closeModal",
                OnFailure = "showMessage"
            } ))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden( "id", Model )
            ;

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        }
    </div>
</div>


<script>

    function closeModal() {
        $("#modal-container").modal("hide");
    }

    function showMessage() {
        $("#MessageToClient").html("<div class='alert alert-danger'> <i class='fa fa-exclamation-triangle fa-2x'> </i> " +
            " An error has occurred while processing your request. <p> Your organization's administrators have been notified of this problem.</p></div>");
    }

</script>

PerformanceManagement/PerformanceManagement/Views/MyCommitment/_Edit.cshtml
@model PerformanceManagement.Application.PerformanceManagement.MyCommitment.ViewModels.MyCommitmenteEditItemVm

<div data-role="page">
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</div>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Edit Commitment</h4>
</div>

<div class="modal-body">

    <p id="MessageToClient" class="text-danger"></p>

    @using ( Ajax.BeginForm( "Edit", "MyCommitment",
                new AjaxOptions
                {
                    HttpMethod = "POST",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "user-evaluations",
                    OnSuccess = "closeModal",
                    OnFailure = "showMessage"
                } ) )
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary( false, "", new { @class = "text-danger" } )

        @Html.HiddenFor( model => model.CVid )

        <div class="form-horizontal">
            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.Year, columns: 2, required: true )
                <div class="col-md-3">
                    @Html.EditorFor( model => model.Year )
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabel( "Category", columns: 2, required: true )
                <div class="col-md-6">
                    @Html.DropDownListFor( m => m.PerformanceCategoryId, Model.PerformanceCategories, new { @class = "form-control" } )
                    <input type="text" id="baseline" class="form-control" readonly="readonly">
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.CommitmentValue, columns: 2, required: true )
                <div class="col-md-10">
                    @Html.EditorFor( model => model.CommitmentValue )
                </div>
            </div>

            <div class="form-group">
                @Html.BootstrapLabelFor( model => model.Description, columns: 2, required: false )
                <div class="col-md-10">
                    @Html.EditorFor( model => model.Description )
                </div>
            </div>

        </div>

        <br />
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>

    }
</div>

<script>
        $(document).ready(function() {
            var dict = []; // create an empty array

            $.ajax({
                type: 'POST',
                url: '@Url.Action( "GetPerformanceCategories" )',
                dataType: 'json',
                success: function (results) {
                    // results contains the JSON formatted list
                    // of states passed from the controller
                    $.each(results,
                        function(i, result) {
                            // result is the json object returned : properties are in camel case because we using Json.NET serializer
                            // result.description instead of result.escription
                            /* ---------------------------------------------------------------------------------------- */
                            $("#PerformanceCategoryId")
                                .append('<option value="' + result.id + '">' + result.description + '</option>');

                            // set the selected items
                            $('#PerformanceCategoryId').val(@Model.PerformanceCategoryId);

                            if (@Model.PerformanceCategoryId == result.id) {
                                $("#baseline").val(result.baseLine);
                            }

                            // create dictionary items
                            dict[result.id] = result.baseLine;
                        });
                },
                error: function(ex) {
                    alert('Failed to retrieve items.' + ex);
                }
            });
            // Populate Dropdownlist

            //Dropdownlist Selectedchange event
            $('#PerformanceCategoryId').on('change', function () {
                // Get the drop down value
                var key = this.value;
                // Pull value out of dictionary using key obtained
                var value = dict[key];
                // Set the text box to the dictionary value
                $("#baseline").val(value);
            });

            return false;
    });


    function closeModal() {
        $("#modal-container").modal("hide");
    }

    function showMessage() {
        $("#MessageToClient").html("<div class='alert alert-danger'> <i class='fa fa-exclamation-triangle fa-2x'> </i> " +
            " An error has occurred while processing your request. <p> Your organization's administrators have been notified of this problem.</p></div>");
    }
</script>